import {
  Job,
  Candidate,
  Application,
  Organization,
  Interview,
  Offer,
  JobCapabilityModel,
  CandidateClaim,
  EvidenceItem,
} from '@ats/shared';
import { aiService } from './services/ai.service';
import { atsStore, StoredUser } from './models/store';
import { hashPassword } from './utils/security';
import { logger } from './utils/logger';

export async function seedDatabase() {
  // 1. Initial Organizations
  const org1: Organization = {
    id: 'org-1',
    name: 'InnovateCorp Technologies',
    slug: 'innovatecorp',
    plan: 'enterprise',
    status: 'active',
    domain: 'innovatecorp.com',
    settings: {
      enableAiScreening: true,
      defaultCurrency: 'USD',
      autoReplyEmail: true,
    },
    createdBy: 'user-recruiter-1',
    createdAt: '2026-07-01T00:00:00.000Z',
    updatedAt: '2026-07-01T00:00:00.000Z',
  };

  const org2: Organization = {
    id: 'org-2',
    name: 'ApexCloud Systems',
    slug: 'apexcloud',
    plan: 'growth',
    status: 'active',
    domain: 'apexcloud.io',
    settings: {
      enableAiScreening: true,
      defaultCurrency: 'USD',
      autoReplyEmail: true,
    },
    createdBy: 'user-recruiter-2',
    createdAt: '2026-07-15T00:00:00.000Z',
    updatedAt: '2026-07-15T00:00:00.000Z',
  };

  // 2. Initial Users
  const adminPass = await hashPassword('VerityAdmin@2026');
  const recruiterPass = await hashPassword('Recruiter@2026');
  const candidatePass = await hashPassword('Candidate@2026');
  const recruiter2Pass = await hashPassword('ApexRecruiter@2026');

  const initialUsers: StoredUser[] = [
    {
      id: 'user-admin-1',
      email: 'admin@verity.ai',
      passwordHash: adminPass,
      firstName: 'System',
      lastName: 'Administrator',
      role: 'admin',
      status: 'active',
      createdAt: '2026-07-01T00:00:00.000Z',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'user-recruiter-1',
      email: 'recruiter@innovatecorp.com',
      passwordHash: recruiterPass,
      firstName: 'Sarah',
      lastName: 'Jenkins',
      role: 'recruiter',
      organizationId: 'org-1',
      status: 'active',
      createdAt: '2026-07-01T00:00:00.000Z',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'user-recruiter-2',
      email: 'recruiter@apexcloud.io',
      passwordHash: recruiter2Pass,
      firstName: 'David',
      lastName: 'Sterling',
      role: 'recruiter',
      organizationId: 'org-2',
      status: 'active',
      createdAt: '2026-07-15T00:00:00.000Z',
      updatedAt: '2026-07-15T00:00:00.000Z',
    },
    {
      id: 'user-candidate-1',
      email: 'candidate@elena.dev',
      passwordHash: candidatePass,
      firstName: 'Elena',
      lastName: 'Rostova',
      role: 'candidate',
      candidateProfileId: 'cand-1',
      status: 'active',
      createdAt: '2026-07-20T00:00:00.000Z',
      updatedAt: '2026-07-20T00:00:00.000Z',
    },
  ];

  // 3. Initial Jobs
  const initialJobs: Job[] = [
    {
      id: 'job-1',
      organizationId: 'org-1',
      title: 'Senior Full-Stack Engineer',
      department: 'Core Engineering',
      location: 'San Francisco, CA (Hybrid / Remote)',
      type: 'full-time',
      experienceLevel: 'senior',
      minYearsExperience: 4,
      maxYearsExperience: 8,
      salaryMin: 155000,
      salaryMax: 195000,
      currency: 'USD',
      description: 'Architect and build high-scale cloud platforms using modern React and Node.js microservices.',
      responsibilities: [
        'Architect and implement scalable REST/GraphQL APIs.',
        'Collaborate with product and design teams.',
        'Optimize throughput, Redis caching, and database queries.',
      ],
      requirements: [
        '4+ years professional full-stack development experience.',
        'Strong expertise in TypeScript, React, and Node.js.',
      ],
      requiredSkills: ['TypeScript', 'React', 'Node.js', 'Express', 'MongoDB', 'AWS'],
      preferredSkills: ['Redis', 'Docker', 'Tailwind CSS'],
      status: 'published',
      openingsCount: 2,
      applicationsCount: 2,
      createdBy: 'user-recruiter-1',
      createdAt: '2026-07-20T10:00:00.000Z',
      updatedAt: '2026-07-20T10:00:00.000Z',
    },
    {
      id: 'job-2',
      organizationId: 'org-1',
      title: 'Staff AI / Machine Learning Engineer',
      department: 'Applied AI Research',
      location: 'New York, NY (Hybrid / Remote)',
      type: 'full-time',
      experienceLevel: 'lead',
      minYearsExperience: 6,
      salaryMin: 185000,
      salaryMax: 240000,
      currency: 'USD',
      description: 'Lead generative AI product pipelines and LLM evaluation harnesses using AWS Bedrock.',
      responsibilities: ['Deploy production LLM pipelines and RAG architectures.'],
      requirements: ['6+ years in Software Engineering with 3+ years in AI/ML.'],
      requiredSkills: ['Python', 'AWS Bedrock', 'PyTorch', 'LLMs', 'Prompt Engineering'],
      preferredSkills: ['FastAPI', 'Docker', 'Kubernetes'],
      status: 'published',
      openingsCount: 1,
      applicationsCount: 1,
      createdBy: 'user-recruiter-1',
      createdAt: '2026-07-25T14:30:00.000Z',
      updatedAt: '2026-07-25T14:30:00.000Z',
    },
    {
      id: 'job-3',
      organizationId: 'org-2',
      title: 'Cloud DevOps Architect (ApexCloud)',
      department: 'Infrastructure',
      location: 'Austin, TX',
      type: 'full-time',
      experienceLevel: 'senior',
      minYearsExperience: 5,
      salaryMin: 165000,
      salaryMax: 210000,
      currency: 'USD',
      description: 'Lead multi-region AWS cloud platform operations at ApexCloud.',
      responsibilities: ['Architect multi-region Kubernetes clusters with Terraform.'],
      requirements: ['5+ years DevOps experience.'],
      requiredSkills: ['AWS', 'Kubernetes', 'Docker', 'Terraform'],
      preferredSkills: ['Go', 'Python'],
      status: 'published',
      openingsCount: 1,
      applicationsCount: 1,
      createdBy: 'user-recruiter-2',
      createdAt: '2026-08-01T09:15:00.000Z',
      updatedAt: '2026-08-01T09:15:00.000Z',
    },
  ];

  // 4. Initial Candidates
  const initialCandidates: Candidate[] = [
    {
      id: 'cand-1',
      userId: 'user-candidate-1',
      organizationId: 'org-1',
      firstName: 'Elena',
      lastName: 'Rostova',
      email: 'candidate@elena.dev',
      phone: '+1 (415) 892-4412',
      location: 'San Francisco, CA',
      headline: 'Senior Full-Stack Architect | React, Node.js & AWS',
      summary: 'Passionate full-stack engineer with 6+ years designing robust web applications.',
      skills: ['TypeScript', 'React', 'Node.js', 'Express', 'MongoDB', 'AWS', 'Redis', 'Docker'],
      experience: [
        {
          title: 'Senior Full-Stack Engineer',
          company: 'Nexus Cloud Platforms',
          startDate: '2022-03',
          endDate: 'Present',
          current: true,
          description: 'Architected high-throughput React/Node.js microservices.',
        },
      ],
      education: [
        {
          institution: 'UC Berkeley',
          degree: 'B.S. in Computer Science',
          graduationYear: 2019,
        },
      ],
      status: 'active',
      tags: ['Top Tier', 'TypeScript Specialist'],
      comments: [
        {
          id: 'comm-1',
          authorId: 'user-recruiter-1',
          authorName: 'Sarah Jenkins',
          authorRole: 'recruiter',
          content: 'Strong cultural fit and stellar system design track record.',
          createdAt: '2026-08-03T10:00:00.000Z',
        },
      ],
      createdAt: '2026-07-20T11:00:00.000Z',
      updatedAt: '2026-07-20T11:00:00.000Z',
    },
    {
      id: 'cand-2',
      organizationId: 'org-1',
      firstName: 'Marcus',
      lastName: 'Vance',
      email: 'marcus.vance@aiworks.org',
      phone: '+1 (646) 321-7789',
      location: 'New York, NY',
      headline: 'Lead AI Engineer | LLMs & AWS Bedrock Specialist',
      summary: 'AI practitioner specializing in generative AI workflows and RAG pipelines.',
      skills: ['Python', 'AWS Bedrock', 'PyTorch', 'LLMs', 'Prompt Engineering', 'LangChain'],
      experience: [
        {
          title: 'Staff AI Engineer',
          company: 'Cognitive Dynamics',
          startDate: '2021-08',
          endDate: 'Present',
          current: true,
        },
      ],
      education: [
        {
          institution: 'Columbia University',
          degree: 'M.S. in Computer Science',
          graduationYear: 2018,
        },
      ],
      status: 'active',
      tags: ['AI Expert', 'Bedrock'],
      comments: [],
      createdAt: '2026-07-25T15:20:00.000Z',
      updatedAt: '2026-07-25T15:20:00.000Z',
    },
    {
      id: 'cand-3',
      organizationId: 'org-1',
      firstName: 'Devon',
      lastName: 'Sterling',
      email: 'devon.sterling@sysscale.io',
      phone: '+1 (206) 555-0194',
      location: 'Seattle, WA (Remote)',
      headline: 'Principal Backend Engineer | Distributed Systems & Node.js',
      summary: 'High-scale infrastructure architect with 8+ years designing fault-tolerant distributed services and event brokers.',
      skills: ['TypeScript', 'Node.js', 'Distributed Systems', 'Database Modeling', 'AWS', 'Docker'],
      experience: [
        {
          title: 'Principal Systems Architect',
          company: 'HyperScale Networks',
          startDate: '2020-04',
          endDate: 'Present',
          current: true,
          description: 'Architected event-driven message mesh handling 1.2M msgs/sec.',
        },
      ],
      education: [
        {
          institution: 'University of Washington',
          degree: 'B.S. in Computer Engineering',
          graduationYear: 2017,
        },
      ],
      status: 'active',
      tags: ['Distributed Systems', 'Staff Engineer', 'High Throughput'],
      comments: [],
      createdAt: '2026-07-28T09:00:00.000Z',
      updatedAt: '2026-07-28T09:00:00.000Z',
    },
  ];

  // 5. Initial Applications
  const elenaScore = await aiService.evaluateCandidateFit(initialJobs[0], initialCandidates[0]);
  const marcusScore = await aiService.evaluateCandidateFit(initialJobs[1], initialCandidates[1]);

  const initialApplications: Application[] = [
    {
      id: 'app-1',
      organizationId: 'org-1',
      jobId: initialJobs[0].id,
      jobTitle: initialJobs[0].title,
      candidateId: initialCandidates[0].id,
      candidate: initialCandidates[0],
      stage: 'interview',
      status: 'active',
      aiScoreCard: elenaScore,
      notes: [],
      timeline: [
        {
          id: 't-1',
          stage: 'applied',
          title: 'Application Received',
          description: 'Direct submission.',
          timestamp: '2026-08-02T11:00:00.000Z',
          actorName: 'Candidate',
        },
        {
          id: 't-2',
          stage: 'interview',
          title: 'Advanced to Interview',
          description: 'Technical System Design scheduled.',
          timestamp: '2026-08-03T10:15:00.000Z',
          actorName: 'Sarah Jenkins',
        },
      ],
      appliedAt: '2026-08-02T11:00:00.000Z',
      updatedAt: '2026-08-03T10:15:00.000Z',
    },
    {
      id: 'app-2',
      organizationId: 'org-1',
      jobId: initialJobs[1].id,
      jobTitle: initialJobs[1].title,
      candidateId: initialCandidates[1].id,
      candidate: initialCandidates[1],
      stage: 'evaluation',
      status: 'active',
      aiScoreCard: marcusScore,
      notes: [],
      timeline: [
        {
          id: 't-3',
          stage: 'applied',
          title: 'Application Received',
          description: 'Submission via portal.',
          timestamp: '2026-08-03T15:20:00.000Z',
          actorName: 'Candidate',
        },
      ],
      appliedAt: '2026-08-03T15:20:00.000Z',
      updatedAt: '2026-08-03T15:20:00.000Z',
    },
    {
      id: 'app-3',
      organizationId: 'org-1',
      jobId: initialJobs[0].id,
      jobTitle: initialJobs[0].title,
      candidateId: initialCandidates[2].id,
      candidate: initialCandidates[2],
      stage: 'interview',
      status: 'active',
      aiScoreCard: elenaScore,
      notes: [],
      timeline: [
        {
          id: 't-4',
          stage: 'applied',
          title: 'Application Received',
          description: 'Direct submission via portal.',
          timestamp: '2026-08-03T18:00:00.000Z',
          actorName: 'Candidate',
        },
        {
          id: 't-5',
          stage: 'interview',
          title: 'Technical Panel Scheduled',
          description: 'Distributed Systems & Reliability Architecture.',
          timestamp: '2026-08-04T09:30:00.000Z',
          actorName: 'Sarah Jenkins',
        },
      ],
      appliedAt: '2026-08-03T18:00:00.000Z',
      updatedAt: '2026-08-04T09:30:00.000Z',
    },
  ];

  // 6. Initial Interviews
  const initialInterviews: Interview[] = [
    {
      id: 'int-1',
      organizationId: 'org-1',
      applicationId: 'app-1',
      jobId: 'job-1',
      candidateId: 'cand-1',
      jobTitle: 'Senior Full-Stack Engineer',
      candidateName: 'Elena Rostova',
      candidateEmail: 'candidate@elena.dev',
      interviewerNames: ['Sarah Jenkins', 'Alex Thorne (Engineering Lead)'],
      interviewType: 'technical',
      scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days in future
      durationMinutes: 60,
      meetingLink: 'https://meet.google.com/verity-elena-interview',
      location: 'Remote (Google Meet)',
      status: 'scheduled',
      notes: 'System architecture deep dive and distributed caching questions.',
      createdBy: 'user-recruiter-1',
      createdAt: '2026-08-03T10:30:00.000Z',
      updatedAt: '2026-08-03T10:30:00.000Z',
    },
  ];

  // 7. Initial Offers
  const initialOffers: Offer[] = [
    {
      id: 'off-1',
      organizationId: 'org-1',
      applicationId: 'app-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      candidateName: 'Elena Rostova',
      candidateEmail: 'candidate@elena.dev',
      jobTitle: 'Senior Full-Stack Engineer',
      baseSalary: 180000,
      currency: 'USD',
      equity: '0.15% ISO Options',
      bonus: '15% Annual Target Performance Bonus',
      startDate: '2026-09-01T00:00:00.000Z',
      expirationDate: '2026-08-25T00:00:00.000Z',
      customTerms: 'Standard health, vision, dental, and 401(k) matching package.',
      status: 'draft',
      createdBy: 'user-recruiter-1',
      createdAt: '2026-08-04T12:00:00.000Z',
      updatedAt: '2026-08-04T12:00:00.000Z',
    },
  ];

  // 8. Initial Capability Model (Phase 3)
  const initialCapabilityModel: JobCapabilityModel = {
    id: 'cap-model-1',
    jobId: 'job-1',
    organizationId: 'org-1',
    version: 1,
    status: 'approved',
    capabilities: [
      {
        id: 'cap-1',
        name: 'TypeScript & Type Systems',
        category: 'languages_frameworks',
        description: 'Advanced static typing, generic abstractions, AST transformations, and strict compiler configurations.',
        importance: 'critical',
        expectedProficiency: 'advanced',
        evaluationMethods: ['coding_challenge', 'debugging_scenario', 'code_review'],
        dependencies: [],
        transferableConcepts: ['JavaScript ESNext', 'Flow', 'Rust Type System', 'C# Generics'],
        evidenceRequirements: ['Demonstrated experience authoring complex generic types and strict type guards in production'],
        freshnessRequirements: 'Active usage within the past 12 months',
        confidenceScore: 0.98,
      },
      {
        id: 'cap-2',
        name: 'React Architecture & State Lifecycle',
        category: 'languages_frameworks',
        description: 'Component lifecycle optimization, custom hook composition, virtual DOM reconciliation, and state isolation.',
        importance: 'high',
        expectedProficiency: 'advanced',
        evaluationMethods: ['coding_challenge', 'system_design', 'debugging_scenario'],
        dependencies: ['TypeScript & Type Systems'],
        transferableConcepts: ['Vue.js', 'SolidJS', 'Svelte', 'Component-Driven Architecture'],
        evidenceRequirements: ['Shipped production SPAs with concurrent rendering and custom hooks architecture'],
        freshnessRequirements: 'Active usage within the past 12 months',
        confidenceScore: 0.95,
      },
      {
        id: 'cap-3',
        name: 'Node.js Asynchronous Runtime',
        category: 'languages_frameworks',
        description: 'Event loop mechanics, stream processing, worker threads, and backpressure management.',
        importance: 'critical',
        expectedProficiency: 'advanced',
        evaluationMethods: ['technical_qa', 'debugging_scenario', 'system_design'],
        dependencies: ['TypeScript & Type Systems'],
        transferableConcepts: ['Go concurrency', 'Python asyncio', 'Event-Driven Architecture'],
        evidenceRequirements: ['Engineered high-concurrency Node.js APIs handling asynchronous I/O and stream processing'],
        freshnessRequirements: 'Active usage within the past 12 months',
        confidenceScore: 0.96,
      },
      {
        id: 'cap-4',
        name: 'Distributed Systems & API Design',
        category: 'systems_architecture',
        description: 'Designing fault-tolerant, horizontally scalable APIs with circuit breaking, rate limiting, and event brokers.',
        importance: 'high',
        expectedProficiency: 'advanced',
        evaluationMethods: ['system_design', 'technical_qa', 'transfer_test'],
        dependencies: [],
        transferableConcepts: ['Microservices', 'Event-Driven Architecture', 'CAP Theorem', 'Idempotency'],
        evidenceRequirements: ['Led architecture reviews and created RFCs for distributed service boundaries'],
        freshnessRequirements: 'Active usage within the past 24 months',
        confidenceScore: 0.92,
      },
      {
        id: 'cap-5',
        name: 'Database Modeling & Index Optimization',
        category: 'data_storage',
        description: 'Data normalization/denormalization trade-offs, compound index selection, and transaction isolation levels.',
        importance: 'high',
        expectedProficiency: 'intermediate',
        evaluationMethods: ['technical_qa', 'debugging_scenario', 'coding_challenge'],
        dependencies: [],
        transferableConcepts: ['PostgreSQL', 'MongoDB', 'Query Planning', 'ACID Transactions'],
        evidenceRequirements: ['Schema design with compound indexes and query optimization for high-read throughput'],
        freshnessRequirements: 'Active usage within the past 24 months',
        confidenceScore: 0.9,
      },
    ],
    relationships: [
      {
        id: 'rel-1',
        sourceName: 'TypeScript & Type Systems',
        targetName: 'React Architecture & State Lifecycle',
        relationshipType: 'prerequisite_for',
        strength: 0.9,
        explanation: 'Strict TypeScript patterns form the foundation for robust enterprise React component libraries.',
      },
      {
        id: 'rel-2',
        sourceName: 'TypeScript & Type Systems',
        targetName: 'Node.js Asynchronous Runtime',
        relationshipType: 'builds_upon',
        strength: 0.88,
        explanation: 'TypeScript builds upon the Node.js runtime to create type-safe backend microservices.',
      },
      {
        id: 'rel-3',
        sourceName: 'Database Modeling & Index Optimization',
        targetName: 'Distributed Systems & API Design',
        relationshipType: 'frequently_paired_with',
        strength: 0.85,
        explanation: 'Effective distributed systems require resilient data storage layers and optimized query patterns.',
      },
    ],
    originalJdSnapshot: {
      title: initialJobs[0].title,
      description: initialJobs[0].description,
      requirements: initialJobs[0].requirements,
      requiredSkills: initialJobs[0].requiredSkills,
      experienceLevel: initialJobs[0].experienceLevel,
    },
    aiProviderUsed: 'AWS Bedrock (Claude 3.5 Sonnet)',
    modelName: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    compilationDurationMs: 1420,
    modifications: [
      {
        id: 'mod-1',
        action: 'add_capability',
        details: 'Initial AI Capability Model generation via AWS Bedrock Claude 3.5 Sonnet',
        modifiedBy: 'AI Capability Compiler',
        timestamp: '2026-08-01T10:00:00.000Z',
      },
      {
        id: 'mod-2',
        action: 'approve',
        details: 'Approved by Sarah Jenkins for candidate proof-of-ability screening',
        modifiedBy: 'user-recruiter-1',
        timestamp: '2026-08-01T10:15:00.000Z',
      },
    ],
    approvedBy: 'user-recruiter-1',
    approvedAt: '2026-08-01T10:15:00.000Z',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:15:00.000Z',
  };

  // 9. Initial Claims & Multi-Stage Evidence (Phase 4)
  const elenaClaims: CandidateClaim[] = [
    {
      id: 'claim-1',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'TypeScript & Type Systems',
      claimedProficiency: 'expert',
      claimSource: 'Resume Technical Skills',
      excerpt: 'Lead TypeScript Architect with 6+ years experience.',
      verificationState: 'VERIFIED',
      createdAt: '2026-07-20T11:00:00.000Z',
    },
    {
      id: 'claim-2',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'React Architecture & State Lifecycle',
      claimedProficiency: 'advanced',
      claimSource: 'Resume Work Experience',
      excerpt: 'Architected high-scale SPAs with React and Redux.',
      verificationState: 'VERIFIED',
      createdAt: '2026-07-20T11:00:00.000Z',
    },
    {
      id: 'claim-3',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Node.js Asynchronous Runtime',
      claimedProficiency: 'advanced',
      claimSource: 'Resume Work Experience',
      excerpt: 'Built high-throughput Node.js microservices.',
      verificationState: 'VERIFIED',
      createdAt: '2026-07-20T11:00:00.000Z',
    },
    {
      id: 'claim-4',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Cloud Platform & Containerization',
      claimedProficiency: 'intermediate',
      claimSource: 'Resume Work Experience',
      excerpt: 'Deployed microservices using AWS and Docker.',
      verificationState: 'PARTIALLY_VERIFIED',
      createdAt: '2026-07-20T11:00:00.000Z',
    },
  ];

  const elenaEvidence: EvidenceItem[] = [
    {
      id: 'ev-1',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'TypeScript & Type Systems',
      sourceType: 'coding_task',
      title: 'Verity Algorithmic & Generics Assessment',
      summary: 'Candidate solved advanced generic constraint puzzle and conditional AST parser in 18 minutes with 100% test coverage.',
      sourceScore: 98,
      state: 'supports',
      reliabilityWeight: 1.0,
      stageRecorded: 'assessment',
      createdAt: '2026-08-02T14:00:00.000Z',
    },
    {
      id: 'ev-2',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'TypeScript & Type Systems',
      sourceType: 'interview',
      title: 'Technical Panel Interview Evaluation',
      summary: 'Flawlessly walked through distributed type safety and interface segregation principles.',
      sourceScore: 95,
      state: 'supports',
      reliabilityWeight: 0.85,
      authorName: 'Alex Thorne (Engineering Lead)',
      stageRecorded: 'interview',
      createdAt: '2026-08-03T11:30:00.000Z',
    },
    {
      id: 'ev-3',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'React Architecture & State Lifecycle',
      sourceType: 'github_project',
      title: 'Public Open Source React UI Library',
      summary: 'Verified GitHub repository with 1,200+ stars demonstrating custom state hooks and concurrent rendering.',
      sourceScore: 92,
      state: 'supports',
      reliabilityWeight: 0.8,
      sourceUrl: 'https://github.com/elena/react-fluid-state',
      stageRecorded: 'applied',
      createdAt: '2026-08-02T11:00:00.000Z',
    },
    {
      id: 'ev-4',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Docker & Containerization',
      sourceType: 'coding_task',
      title: 'Multi-Stage Dockerfile & Container Optimization Challenge',
      summary: 'Verified multi-stage container optimization challenge reducing image size by 74% and configuring rootless runtime.',
      sourceScore: 94,
      state: 'supports',
      reliabilityWeight: 0.9,
      stageRecorded: 'assessment',
      createdAt: new Date(Date.now() - 8 * 30.44 * 24 * 60 * 60 * 1000).toISOString(), // Exactly 8 months old
    },
    {
      id: 'ev-5',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Node.js Asynchronous Runtime',
      sourceType: 'coding_task',
      title: 'Event Loop & Stream Backpressure Challenge',
      summary: 'Engineered high-concurrency Node.js transform stream pipeline with zero memory leak.',
      sourceScore: 96,
      state: 'supports',
      reliabilityWeight: 0.95,
      stageRecorded: 'assessment',
      createdAt: '2026-08-02T14:30:00.000Z',
    },
    {
      id: 'ev-6',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Database Modeling & Index Optimization',
      sourceType: 'interview',
      title: 'Relational Query Planning & Compound Indexing',
      summary: 'Demonstrated deep SQL transaction isolation, ACID guarantees, and B-Tree index optimization.',
      sourceScore: 90,
      state: 'supports',
      reliabilityWeight: 0.85,
      stageRecorded: 'interview',
      createdAt: new Date(Date.now() - 14 * 30.44 * 24 * 60 * 60 * 1000).toISOString(), // 14 months old (Low volatility SQL)
    },
  ];

  atsStore.seedInitialData(
    initialUsers,
    [org1, org2],
    initialJobs,
    initialCandidates,
    initialApplications,
    initialInterviews,
    initialOffers
  );

  await atsStore.saveJobCapabilityModel(initialCapabilityModel);
  await atsStore.saveCandidateClaims(elenaClaims);
  for (const ev of elenaEvidence) {
    await atsStore.addEvidenceItem(ev);
  }

  // Seed CandidateCapabilities for cand-1
  await atsStore.saveCandidateCapability({
    id: 'cc_cand-1_typescript',
    candidateId: 'cand-1',
    organizationId: 'org-1',
    capabilityName: 'TypeScript & Type Systems',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 94,
    evidenceCount: 2,
    evidenceQualityScore: 95,
    evidenceDiversityScore: 85,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-1_react',
    candidateId: 'cand-1',
    organizationId: 'org-1',
    capabilityName: 'React Architecture & State Lifecycle',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 91,
    evidenceCount: 1,
    evidenceQualityScore: 92,
    evidenceDiversityScore: 70,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-1_nodejs',
    candidateId: 'cand-1',
    organizationId: 'org-1',
    capabilityName: 'Node.js Asynchronous Runtime',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 95,
    evidenceCount: 1,
    evidenceQualityScore: 96,
    evidenceDiversityScore: 80,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-1_docker',
    candidateId: 'cand-1',
    organizationId: 'org-1',
    capabilityName: 'Docker & Containerization',
    category: 'cloud_devops',
    verificationState: 'VERIFIED',
    confidenceScore: 88,
    evidenceCount: 1,
    evidenceQualityScore: 90,
    evidenceDiversityScore: 75,
    freshnessDate: new Date(Date.now() - 8 * 30.44 * 24 * 60 * 60 * 1000).toISOString(), // 8 months old
    evidenceBreakdown: [],
    updatedAt: new Date(Date.now() - 8 * 30.44 * 24 * 60 * 60 * 1000).toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-1_database',
    candidateId: 'cand-1',
    organizationId: 'org-1',
    capabilityName: 'Database Modeling & Index Optimization',
    category: 'data_storage',
    verificationState: 'VERIFIED',
    confidenceScore: 87,
    evidenceCount: 1,
    evidenceQualityScore: 88,
    evidenceDiversityScore: 70,
    freshnessDate: new Date(Date.now() - 14 * 30.44 * 24 * 60 * 60 * 1000).toISOString(), // 14 months old (Low Volatility SQL)
    evidenceBreakdown: [],
    updatedAt: new Date(Date.now() - 14 * 30.44 * 24 * 60 * 60 * 1000).toISOString(),
  });

  // Seed CandidateCapabilities for cand-2
  await atsStore.saveCandidateCapability({
    id: 'cc_cand-2_python',
    candidateId: 'cand-2',
    organizationId: 'org-1',
    capabilityName: 'Python',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 85,
    evidenceCount: 1,
    evidenceQualityScore: 85,
    evidenceDiversityScore: 50,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  // Seed CandidateCapabilities for cand-3 (Devon Sterling)
  await atsStore.saveCandidateCapability({
    id: 'cc_cand-3_typescript',
    candidateId: 'cand-3',
    organizationId: 'org-1',
    capabilityName: 'TypeScript & Type Systems',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 88,
    evidenceCount: 2,
    evidenceQualityScore: 90,
    evidenceDiversityScore: 75,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-3_nodejs',
    candidateId: 'cand-3',
    organizationId: 'org-1',
    capabilityName: 'Node.js Asynchronous Runtime',
    category: 'languages_frameworks',
    verificationState: 'VERIFIED',
    confidenceScore: 97,
    evidenceCount: 3,
    evidenceQualityScore: 98,
    evidenceDiversityScore: 90,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-3_distributed',
    candidateId: 'cand-3',
    organizationId: 'org-1',
    capabilityName: 'Distributed Systems & API Design',
    category: 'systems_architecture',
    verificationState: 'VERIFIED',
    confidenceScore: 96,
    evidenceCount: 3,
    evidenceQualityScore: 95,
    evidenceDiversityScore: 85,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateCapability({
    id: 'cc_cand-3_database',
    candidateId: 'cand-3',
    organizationId: 'org-1',
    capabilityName: 'Database Modeling & Index Optimization',
    category: 'data_storage',
    verificationState: 'VERIFIED',
    confidenceScore: 92,
    evidenceCount: 2,
    evidenceQualityScore: 90,
    evidenceDiversityScore: 80,
    freshnessDate: new Date().toISOString(),
    evidenceBreakdown: [],
    updatedAt: new Date().toISOString(),
  });

  // Seed 6-Stage Chronological Evidence Events for Elena Rostova (cand-1)
  const elenaTimelineEvents = [
    {
      id: 'ee_cand1_stage1_resume',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'TypeScript & Type Systems',
      eventType: 'claim_extracted' as const,
      title: 'Resume Parsing & Claim Ingestion',
      description: 'Extracted validated claim: 6+ yrs Full-Stack development with TypeScript, React, and Node.js microservices at Nexus Cloud.',
      actorName: 'AI Resume Parser',
      actorRole: 'system',
      stageName: 'Resume' as const,
      sourceType: 'resume' as const,
      score: 88,
      state: 'supports' as const,
      reliabilityWeight: 0.65,
      details: {
        rawExcerpt: 'Senior Full-Stack Architect at Nexus Cloud Platforms (2022-Present). Led core TypeScript migration.',
        section: 'Work Experience',
      },
      timestamp: '2026-08-01T10:00:00.000Z',
    },
    {
      id: 'ee_cand1_stage2_project',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'React Architecture & State Lifecycle',
      eventType: 'project_verified' as const,
      title: 'GitHub Open-Source Project Verification',
      description: 'Verified public repository "react-fluid-state" with 1,200+ GitHub stars, showcasing custom hook composition and concurrent rendering.',
      actorName: 'GitHub Evidence Connector',
      actorRole: 'system',
      stageName: 'Project' as const,
      sourceType: 'github_project' as const,
      score: 92,
      state: 'supports' as const,
      reliabilityWeight: 0.85,
      details: {
        repoUrl: 'https://github.com/elena/react-fluid-state',
        stars: 1240,
        license: 'MIT',
        primaryLanguage: 'TypeScript',
      },
      timestamp: '2026-08-01T14:30:00.000Z',
    },
    {
      id: 'ee_cand1_stage3_assessment',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'TypeScript & Type Systems',
      eventType: 'assessment_completed' as const,
      title: 'Adaptive Type System & Generic Challenge',
      description: 'Completed Level 4 adaptive assessment on recursive mapped types, distributive conditional generics, and strict narrowing in 18m.',
      actorName: 'Verity Assessment Engine',
      actorRole: 'system',
      stageName: 'Assessment' as const,
      sourceType: 'assessment' as const,
      score: 95,
      state: 'supports' as const,
      reliabilityWeight: 0.95,
      details: {
        level: 4,
        timeSpent: '18m 24s',
        rubricScore: '28.5 / 30',
        testPassRate: '100%',
      },
      timestamp: '2026-08-02T11:15:00.000Z',
    },
    {
      id: 'ee_cand1_stage4_coding',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Node.js Asynchronous Runtime',
      eventType: 'coding_challenge_completed' as const,
      title: 'Live Transform Stream & Concurrency Execution',
      description: 'Implemented backpressure-safe Node.js Transform Stream with memory leak guard passing all 12 concurrency test fixtures.',
      actorName: 'Verity Code Sandbox',
      actorRole: 'system',
      stageName: 'Coding' as const,
      sourceType: 'coding_task' as const,
      score: 98,
      state: 'supports' as const,
      reliabilityWeight: 1.0,
      details: {
        language: 'TypeScript / Node.js v20',
        memoryFootprint: '14.2 MB (Safe)',
        throughput: '85,000 req/sec',
      },
      timestamp: '2026-08-02T16:00:00.000Z',
    },
    {
      id: 'ee_cand1_stage5_interview',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Distributed Systems & API Design',
      eventType: 'interview_evaluated' as const,
      title: 'Technical Panel Interview Evaluation',
      description: 'Panel deep-dive with Engineering Lead Alex Thorne. Evaluated idempotency keys, distributed rate limiting, and circuit breaking.',
      actorName: 'Alex Thorne (Engineering Lead)',
      actorRole: 'interviewer',
      stageName: 'Interview' as const,
      sourceType: 'interview' as const,
      score: 94,
      state: 'supports' as const,
      reliabilityWeight: 0.9,
      details: {
        recommendation: 'strong_hire',
        rubricCriteria: {
          systemReasoning: 95,
          tradeoffAnalysis: 92,
          communication: 96,
        },
      },
      timestamp: '2026-08-03T11:30:00.000Z',
    },
    {
      id: 'ee_cand1_stage6_transfer',
      candidateId: 'cand-1',
      organizationId: 'org-1',
      capabilityName: 'Distributed Systems & API Design',
      eventType: 'transfer_test_completed' as const,
      title: 'Cross-Domain Transfer Test: Relational to Event-Driven',
      description: 'Completed transfer challenge mapping transactional ACID workflows to eventual consistency saga patterns with compensation logs.',
      actorName: 'Verity Transfer Engine',
      actorRole: 'system',
      stageName: 'Transfer Test' as const,
      sourceType: 'transfer_test' as const,
      score: 96,
      state: 'supports' as const,
      reliabilityWeight: 0.95,
      details: {
        sourceConcept: '2-Phase Commit ACID Transactions',
        targetConcept: 'Orchestrated Saga Pattern with Idempotent Compensation',
        transferStrengthScore: 96,
      },
      timestamp: '2026-08-03T15:45:00.000Z',
    },
  ];

  for (const ev of elenaTimelineEvents) {
    await atsStore.addEvidenceEvent(ev);
  }

  // Seed 6-Stage Chronological Evidence Events for Devon Sterling (cand-3)
  const devonTimelineEvents = [
    {
      id: 'ee_cand3_stage1_resume',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Distributed Systems & API Design',
      eventType: 'claim_extracted' as const,
      title: 'Resume Ingestion: Principal Distributed Systems Architect',
      description: 'Extracted claim: 8+ yrs architecting event-driven message mesh handling 1.2M msgs/sec at HyperScale Networks.',
      actorName: 'AI Resume Parser',
      actorRole: 'system',
      stageName: 'Resume' as const,
      sourceType: 'resume' as const,
      score: 90,
      state: 'supports' as const,
      reliabilityWeight: 0.65,
      timestamp: '2026-08-02T09:00:00.000Z',
    },
    {
      id: 'ee_cand3_stage2_project',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Distributed Systems & API Design',
      eventType: 'project_verified' as const,
      title: 'Raft Consensus Cluster Implementation (Go / TS)',
      description: 'Verified production consensus leader election and log compaction library on GitHub with 800+ stars.',
      actorName: 'GitHub Evidence Connector',
      actorRole: 'system',
      stageName: 'Project' as const,
      sourceType: 'github_project' as const,
      score: 96,
      state: 'supports' as const,
      reliabilityWeight: 0.9,
      timestamp: '2026-08-02T13:00:00.000Z',
    },
    {
      id: 'ee_cand3_stage3_assessment',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Database Modeling & Index Optimization',
      eventType: 'assessment_completed' as const,
      title: 'Distributed Storage & CAP Theorem Assessment',
      description: 'Scored 91% on network partition handling, quorum reads/writes, and compound index strategy.',
      actorName: 'Verity Assessment Engine',
      actorRole: 'system',
      stageName: 'Assessment' as const,
      sourceType: 'assessment' as const,
      score: 91,
      state: 'supports' as const,
      reliabilityWeight: 0.9,
      timestamp: '2026-08-03T10:00:00.000Z',
    },
    {
      id: 'ee_cand3_stage4_coding',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Node.js Asynchronous Runtime',
      eventType: 'coding_challenge_completed' as const,
      title: 'High-Throughput Worker Thread Queue Task',
      description: 'Engineered zero-overhead worker pool processing 250,000 JSON payloads with shared ArrayBuffers.',
      actorName: 'Verity Code Sandbox',
      actorRole: 'system',
      stageName: 'Coding' as const,
      sourceType: 'coding_task' as const,
      score: 97,
      state: 'supports' as const,
      reliabilityWeight: 1.0,
      timestamp: '2026-08-03T14:00:00.000Z',
    },
    {
      id: 'ee_cand3_stage5_interview',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Distributed Systems & API Design',
      eventType: 'interview_evaluated' as const,
      title: 'Distributed Architecture & Fault Recovery Panel',
      description: 'Interviewer Sarah Jenkins and Staff Architect evaluated partition tolerance and zero-downtime database failovers.',
      actorName: 'Sarah Jenkins',
      actorRole: 'recruiter',
      stageName: 'Interview' as const,
      sourceType: 'interview' as const,
      score: 95,
      state: 'supports' as const,
      reliabilityWeight: 0.9,
      timestamp: '2026-08-04T10:30:00.000Z',
    },
    {
      id: 'ee_cand3_stage6_transfer',
      candidateId: 'cand-3',
      organizationId: 'org-1',
      capabilityName: 'Node.js Asynchronous Runtime',
      eventType: 'transfer_test_completed' as const,
      title: 'Transfer Test: Erlang Actor Model to Node.js Microservices',
      description: 'Demonstrated rapid conceptual transfer from Erlang OTP supervisors to Node.js cluster process resilience.',
      actorName: 'Verity Transfer Engine',
      actorRole: 'system',
      stageName: 'Transfer Test' as const,
      sourceType: 'transfer_test' as const,
      score: 93,
      state: 'supports' as const,
      reliabilityWeight: 0.95,
      timestamp: '2026-08-04T15:00:00.000Z',
    },
  ];

  for (const ev of devonTimelineEvents) {
    await atsStore.addEvidenceEvent(ev);
  }

  // Seed Candidate Consents (Phase 9)
  await atsStore.saveCandidateConsent({
    candidateId: 'cand-1',
    allowCrossJobReuse: true,
    allowCrossOrgSharing: true,
    excludedOrganizations: [],
    allowedCapabilities: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateConsent({
    candidateId: 'cand-2',
    allowCrossJobReuse: true,
    allowCrossOrgSharing: false,
    excludedOrganizations: [],
    allowedCapabilities: [],
    updatedAt: new Date().toISOString(),
  });

  await atsStore.saveCandidateConsent({
    candidateId: 'cand-3',
    allowCrossJobReuse: true,
    allowCrossOrgSharing: true,
    excludedOrganizations: [],
    allowedCapabilities: [],
    updatedAt: new Date().toISOString(),
  });

  logger.info('Database seeded with Users, Organizations, Jobs, Candidates, AI Applications, Interviews, Offers, Capability Models, Proof-of-Skill Evidence, and Living Passports.');
}
